server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: servicio-usuarios
          uri: lb://apiusuarios
          predicates:
            - Path=/usuarios/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
