server:
  port: 8087

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: servicio-usuarios
          uri: lb://apiusuarios
          predicates:
            - Path=/usuarios/**

        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/reservas/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
